# Generated by Django 4.1.1 on 2023-08-30 16:06

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
        ('subprojects', '0031_alter_level_percent_alter_step_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevelWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('begin', models.DateField(blank=True, null=True, verbose_name='Begin')),
                ('end', models.DateField(blank=True, null=True, verbose_name='End')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel', verbose_name='Administrative level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='Project')),
            ],
        ),
        migrations.CreateModel(
            name='Wave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('number', models.IntegerField(verbose_name='Number')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'unique_together': {('number',)},
            },
        ),
        migrations.CreateModel(
            name='PeriodWave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('part', cosomis.customers_fields.CustomerIntegerRangeField(verbose_name='Part')),
                ('begin', models.DateField(verbose_name='Begin')),
                ('end', models.DateField(verbose_name='End')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('administrative_levels', models.ManyToManyField(default=[], to='process_manager.administrativelevelwave', verbose_name='Administrative level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='Project')),
                ('wave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.wave', verbose_name='Wave')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='administrativelevelwave',
            name='wave',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process_manager.wave', verbose_name='Wave'),
        ),
        migrations.AlterUniqueTogether(
            name='administrativelevelwave',
            unique_together={('administrative_level', 'wave', 'project')},
        ),
    ]
