# Generated by Django 4.1.1 on 2023-08-29 09:10

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
        ('subprojects', '0031_alter_level_percent_alter_step_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevelAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('amount', cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Amount')),
                ('allocation_date', models.DateField(verbose_name='Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel', verbose_name='Administrative level')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='Project')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
