# Generated by Django 4.1.1 on 2023-09-01 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_bank_alter_administrativelevelallocation_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together={('name',), ('abbreviation',)},
        ),
    ]
