# Generated by Django 4.1.1 on 2023-09-01 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0018_cvd_account_number_cvd_bank_cvd_bank_code_and_more'),
        ('financial', '0003_alter_bank_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevelallocation',
            name='cvd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.cvd', verbose_name='CVD'),
        ),
        migrations.AlterField(
            model_name='administrativelevelallocation',
            name='administrative_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel', verbose_name='Administrative level'),
        ),
    ]
