# Generated by Django 4.1.1 on 2023-09-04 10:17

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0031_alter_level_percent_alter_step_percent_and_more'),
        ('administrativelevels', '0018_cvd_account_number_cvd_bank_cvd_bank_code_and_more'),
        ('financial', '0004_administrativelevelallocation_cvd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativelevelallocation',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='DisbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('amount_requested', cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Amount requested')),
                ('requested_date', models.DateField(verbose_name='Request date')),
                ('motif', models.DateField(blank=True, max_length=255, null=True, verbose_name='Motif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reply_date', models.DateField(verbose_name='Reply date')),
                ('comment_linked_to_reply', models.TextField(blank=True, null=True, verbose_name='Comment related to the request response')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='Project')),
            ],
            options={
                'db_table': 'financial_disbursement_request',
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('amount_disbursed', cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Amount disbursed')),
                ('disbursement_date', models.DateField(verbose_name='Disbursement date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='Project')),
            ],
            options={
                'db_table': 'financial_disbursement',
            },
        ),
        migrations.CreateModel(
            name='BankTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('amount_transferred', cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Amount transferred')),
                ('transfer_date', models.DateField(verbose_name='Transfer date')),
                ('motif', models.DateField(blank=True, max_length=255, null=True, verbose_name='Motif')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('administrative_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel', verbose_name='Administrative level')),
                ('cvd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.cvd', verbose_name='CVD')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project', verbose_name='Project')),
            ],
            options={
                'db_table': 'financial_bank_transfer',
            },
        ),
    ]
