# Generated by Django 4.1.1 on 2023-09-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0018_cvd_account_number_cvd_bank_cvd_bank_code_and_more'),
        ('financial', '0005_alter_administrativelevelallocation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransfer',
            name='cvd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.cvd', verbose_name='CVD'),
        ),
    ]
