# Generated by Django 4.1.1 on 2023-09-04 18:59

import cosomis.customers_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_alter_administrativelevelallocation_allocation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='amount_disbursed_in_dollars',
            field=cosomis.customers_fields.CustomerFloatRangeField(default=None, verbose_name='Amount disbursed in dollars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disbursementrequest',
            name='amount_requested_in_dollars',
            field=cosomis.customers_fields.CustomerFloatRangeField(default=None, verbose_name='Amount requested in dollars'),
            preserve_default=False,
        ),
    ]
