# Generated by Django 4.1.1 on 2023-09-04 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0009_disbursement_amount_disbursed_in_dollars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disbursement',
            name='disbursement_request',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='financial.disbursementrequest', verbose_name='This disbursement is related to the following request'),
            preserve_default=False,
        ),
    ]
