# Generated by Django 4.1.1 on 2023-09-05 13:06

import cosomis.customers_fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0031_alter_level_percent_alter_step_percent_and_more'),
        ('financial', '0010_disbursement_disbursement_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevelallocation',
            name='amount_in_dollars',
            field=cosomis.customers_fields.CustomerFloatRangeField(default=None, verbose_name='Amount allocated in dollars'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrativelevelallocation',
            name='component',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.component', verbose_name='Component (Subcomponent)'),
        ),
        migrations.AlterField(
            model_name='administrativelevelallocation',
            name='amount',
            field=cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Amount allocated'),
        ),
    ]
