# Generated by Django 4.1.1 on 2023-07-31 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
        ('subprojects', '0020_rename_financier_subproject_financiers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignAdministrativeLevelToFacilitator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('facilitator_id', models.CharField(max_length=255)),
                ('activated', models.BooleanField(default=True)),
                ('assign_date', models.DateField(blank=True, null=True)),
                ('unassign_date', models.DateField(blank=True, null=True)),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.project')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assignadministrativeleveltofacilitator',
            constraint=models.UniqueConstraint(condition=models.Q(('activated', True)), fields=('administrative_level', 'project'), name='unique_administrative_level_project_activated'),
        ),
    ]
