# Generated by Django 4.1.1 on 2024-08-12 14:04

from django.db import migrations, models
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=usermanager.models.upload_to_user_photo),
        ),
    ]
