# Generated by Django 4.1.1 on 2026-04-02 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0002_user_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('code', models.CharField(max_length=128, verbose_name='Code')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('asking_datetime', models.DateTimeField(verbose_name='Asking datetime')),
                ('validation_code_ending_datetime', models.DateTimeField(verbose_name='Validation Code Ending datetime')),
                ('motif', models.TextField(verbose_name='Motif')),
                ('already_use', models.BooleanField(default=False, verbose_name='Already Use?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
