# Generated by Django 4.1.1 on 2026-04-03 10:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0003_validationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, default=datetime.datetime(2036, 3, 31, 10, 15, 10, 902080, tzinfo=datetime.timezone.utc), help_text="Permet d'obtenir un nouveau jeton d'accès sans reconnexion.", null=True, verbose_name='Jeton de Rafraîchissement')),
                ('service_name', models.CharField(default='External_API', max_length=100, verbose_name='Nom du Service Tiers')),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2036, 3, 31, 10, 15, 10, 902080, tzinfo=datetime.timezone.utc))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
