# Generated by Django 4.1.1 on 2026-04-11 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0004_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed_once',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2036, 4, 8, 17, 58, 53, 29865, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=datetime.datetime(2036, 4, 8, 17, 58, 53, 29865, tzinfo=datetime.timezone.utc), help_text="Permet d'obtenir un nouveau jeton d'accès sans reconnexion.", null=True, verbose_name='Jeton de Rafraîchissement'),
        ),
    ]
