# Generated by Django 4.1.1 on 2026-05-18 13:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0005_user_password_changed_once_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2036, 5, 15, 13, 25, 23, 540469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=datetime.datetime(2036, 5, 15, 13, 25, 23, 540455, tzinfo=datetime.timezone.utc), help_text="Permet d'obtenir un nouveau jeton d'accès sans reconnexion.", null=True, verbose_name='Jeton de Rafraîchissement'),
        ),
        migrations.AlterField(
            model_name='validationcode',
            name='motif',
            field=models.TextField(verbose_name='Reason'),
        ),
    ]
