# Generated by Django 4.1.1 on 2026-06-09 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0006_alter_usertoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2036, 6, 6, 8, 40, 34, 21255, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=datetime.datetime(2036, 6, 6, 8, 40, 34, 21219, tzinfo=datetime.timezone.utc), help_text="Permet d'obtenir un nouveau jeton d'accès sans reconnexion.", null=True, verbose_name='Jeton de Rafraîchissement'),
        ),
    ]
