# Generated by Django 4.1.1 on 2026-08-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):
    # Note: `makemigrations` also auto-detected drift on UserToken.expires_at/
    # refresh_token (their `default=` appears to evaluate a fresh timestamp at
    # every makemigrations run instead of using a callable) — pre-existing,
    # unrelated to this change, deliberately left untouched here.

    dependencies = [
        ('usermanager', '0007_user_phone_alter_usertoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_anomaly_corrector',
            field=models.BooleanField(default=False),
        ),
    ]
