# Generated by Django 4.1.1 on 2026-09-29 12:47

from django.db import migrations, models
import usermanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanager', '0008_user_is_anomaly_corrector_alter_usertoken_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='expires_at',
            field=models.DateTimeField(default=usermanager.models.default_token_expiry),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='refresh_token',
            field=models.TextField(blank=True, default=usermanager.models.default_token_expiry, help_text="Permet d'obtenir un nouveau jeton d'accès sans reconnexion.", null=True, verbose_name='Jeton de Rafraîchissement'),
        ),
    ]
