"""
Django settings for cosomis project.

Generated by 'django-admin startproject' using Django 1.8.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
from pathlib import Path
import os
import django.conf.locale
from datetime import timedelta
import environ
from django.conf import global_settings
from django.utils.translation import gettext_lazy as _

# https://django-environ.readthedocs.io/en/latest/
env = environ.Env()
env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env(
    'SECRET_KEY',
    default='pl&dkqrq0rj+#n747=@#a-0b(bgb2j#%@f7v4_vp1q84cr7r#$',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DEBUG', False)

ALLOWED_HOSTS = env('ALLOWED_HOSTS', list, ['localhost'])

# Vercel (and any other TLS-terminating proxy) forwards the original scheme in
# this header. Without it Django builds http:// absolute URLs behind https and
# rejects same-origin POSTs as CSRF failures.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True

# Preview deployments get a fresh sub-domain per commit, so the whole
# *.vercel.app space is trusted rather than a single fixed host.
CSRF_TRUSTED_ORIGINS = env(
    'CSRF_TRUSTED_ORIGINS', list, ['https://*.vercel.app'],
)

# Per-deployment program name shown on login and other branded surfaces.
# Defaults to the Togo wording; override per country via the PROGRAM_NAME env var.
PROGRAM_NAME = env(
    'PROGRAM_NAME',
    default='Emergency program to strengthen community resilience and security',
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

CREATED_APPS = [
    'usermanager',
    'administrativelevels',
    'authentication',
    'investments',
    'dashboard',
    'cdd_funnel',
    'utils',
    'assistant',
]

THIRD_PARTY_APPS = [
    'bootstrap4',
    'django_unicorn',
    'django_celery_results',
    'drf_spectacular',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
    'rest_framework.authtoken',

    # https://django-htmx.readthedocs.io/en/latest/installation.html
    'django_htmx',
]

INSTALLED_APPS += CREATED_APPS + THIRD_PARTY_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware', #tries to determine user's language using URL language prefix
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_htmx.middleware.HtmxMiddleware',
]

ROOT_URLCONF = 'cosomis.urls'

AUTH_USER_MODEL = 'usermanager.User'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'cosomis', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                'cosomis.services.overall_variables',  # Called the function which presents the globals variables
                'investments.context_processors.notifications',
                'investments.context_processors.cart_items'
            ],
        },
    },
]

WSGI_APPLICATION = 'cosomis.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

EXTERNAL_DATABASE_NAME = 'cddp'

if env('env', default='') == 'dev':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            #'NAME': '/Users/asucr/Downloads/database1.db',  # This is where you put the name of the db file.
            # If one doesn't exist, it will be created at migration time.
            'NAME': os.path.join(BASE_DIR, 'database1.db'),
        }
    }
else:
    DATABASES = {
        'default': env.db(),
        # EXTERNAL_DATABASE_NAME: env.db('LEGACY_DATABASE_URL')
    }
    

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         #'NAME': '/Users/asucr/Downloads/database1.db',  # This is where you put the name of the db file.
#         # If one doesn't exist, it will be created at migration time.
#         'NAME': os.path.join(BASE_DIR, 'database1.db'),
#     }
#  }

MAX_RESPONSE_DAYS = 3


# Email configuration

EMAIL_BACKEND = env(
    'EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = env('EMAIL_HOST', default='localhost')
EMAIL_PORT = env('EMAIL_PORT', default='25')
EMAIL_USE_TLS = env.bool('EMAIL_USE_TLS', default=False)
EMAIL_HOST_USER = env('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD', default='')
RECIPIENT_EMAIL_DEFAULT = env('RECIPIENT_EMAIL_DEFAULT', default='')

# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]

LANGUAGES = [
    ('en', _('English')), 
    ('fr', _('French')), 
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Serverless builds cannot always run `collectstatic`, so let WhiteNoise fall
# back to the staticfiles finders when STATIC_ROOT was never populated.
WHITENOISE_USE_FINDERS = not os.path.isdir(STATIC_ROOT)
if WHITENOISE_USE_FINDERS:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

FRONTEND_URL_ROOT = env('FRONTEND_URL_ROOT', default='')


LOGIN_URL = '/'

LOGIN_REDIRECT_URL = 'investments:home_investments'

LOGOUT_REDIRECT_URL = LOGIN_URL
# Mapbox
MAPBOX_ACCESS_TOKEN = env('MAPBOX_ACCESS_TOKEN', default='')

DIAGNOSTIC_MAP_LATITUDE = env('DIAGNOSTIC_MAP_LATITUDE', default='8.770198211475261')

DIAGNOSTIC_MAP_LONGITUDE = env('DIAGNOSTIC_MAP_LONGITUDE', default='0.8332327892880187')

DIAGNOSTIC_MAP_ZOOM = env('DIAGNOSTIC_MAP_ZOOM', default='6.29')

DIAGNOSTIC_MAP_WS_BOUND = env(
    'DIAGNOSTIC_MAP_WS_BOUND', default='[-1.6405819530436645, 6.032835821531734]',
)

DIAGNOSTIC_MAP_EN_BOUND = env(
    'DIAGNOSTIC_MAP_EN_BOUND', default='[3.226379659586371, 11.303021230048657]',
)

DIAGNOSTIC_MAP_ISO_CODE = env('DIAGNOSTIC_MAP_ISO_CODE', default='TGO')


# CouchDB

NO_SQL_USER = env('NO_SQL_USER', default='')

NO_SQL_PASS = env('NO_SQL_PASS', default='')

NO_SQL_URL = env('NO_SQL_URL', default='')


# S3
AWS_STORAGE_BUCKET_NAME = env('S3_BUCKET', default='')

AWS_ACCESS_KEY_ID = env('S3_ACCESS', default='')

AWS_SECRET_ACCESS_KEY = env('S3_SECRET', default='')

# Demo/preview deployments run without S3 credentials; uploads then use
# Django's default filesystem storage instead of failing at request time.
if AWS_STORAGE_BUCKET_NAME and AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


#REST API & TOKEN
REST_FRAMEWORK = {
    # https://github.com/tfranzel/drf-spectacular
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework_datatables.renderers.DatatablesRenderer',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'rest_framework_datatables.filters.DatatablesFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework_datatables.pagination.DatatablesPageNumberPagination',
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3650),  # 10 ans (365 jours × 10)
    'REFRESH_TOKEN_LIFETIME': timedelta(days=3650),  # 10 ans aussi si besoin
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
}
AUTHORIZED_USERS_FOR_USER_REGISTRATION_VIA_API = env(
    'AUTHORIZED_USERS_FOR_USER_REGISTRATION_VIA_API', default='',
)



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]

# MIXPANEL
MIXPANEL_TOKEN = env('MIXPANEL_TOKEN', default='')
MIXPANEL_API_SECRET = env('MIXPANEL_API_SECRET', default='')


# MIS API
MIS_API_KEY = env('MIS_API_KEY', default='')
MIS_URL = env('MIS_URL', default='')

# GRM API
GRM_SECRET_KEY_GENRATE = env('GRM_SECRET_KEY_GENRATE', default='')
GRM_URL = env('GRM_URL', default='')


# Portal assistant (assistant/) — read-only chat over the portal's data.
# Without OPENAI_API_KEY the page renders but explains it is not configured.
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
OPENAI_BASE_URL = env('OPENAI_BASE_URL', default='')  # optional, OpenAI-compatible proxy
ASSISTANT_MODEL = env('ASSISTANT_MODEL', default='gpt-5-mini')