# Generated by Django 4.1.1 on 2022-10-12 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0007_delete_village'),
        ('subprojects', '0003_vulnerablegroup_administrative_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VillagePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('subcomponent', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('proposed_men', models.IntegerField(null=True)),
                ('proposed_women', models.IntegerField(null=True)),
                ('estimated_cost', models.FloatField(null=True)),
                ('estimated_beneficiaries', models.IntegerField(null=True)),
                ('climate_changing_contribution', models.TextField(null=True)),
                ('eligibility', models.BooleanField(blank=True, null=True)),
                ('sector', models.CharField(max_length=255, null=True)),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.villagepriority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillageObstacle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('focus_group', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VillageGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('focus_group', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TypeMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.villagepriority')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrioritiesMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('description', models.TextField()),
                ('date_conducted', models.DateTimeField()),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel')),
                ('village_goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.villagegoal')),
                ('village_obstacle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.villageobstacle')),
                ('village_priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.villagepriority')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
