# Generated by Django 4.1.1 on 2022-10-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0005_villagemeeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='villagemeeting',
            name='type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
