# Generated by Django 4.1.1 on 2022-10-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0009_component_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagepriority',
            name='sector',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
