# Generated by Django 4.1.1 on 2022-10-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0010_alter_villagepriority_sector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villagepriority',
            name='climate_changing_contribution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villagepriority',
            name='estimated_beneficiaries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villagepriority',
            name='estimated_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villagepriority',
            name='proposed_men',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villagepriority',
            name='proposed_women',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
