# Generated by Django 4.1.1 on 2022-11-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0011_alter_villagepriority_climate_changing_contribution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='allocation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
