# Generated by Django 4.1.1 on 2023-03-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0016_remove_subproject_allocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='works_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
