# Generated by Django 4.1.1 on 2023-03-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0016_alter_administrativelevel_unique_together'),
        ('subprojects', '0017_alter_subproject_works_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='cantons',
            field=models.ManyToManyField(blank=True, default=[], to='administrativelevels.administrativelevel'),
        ),
    ]
