# Generated by Django 4.1.1 on 2023-03-03 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0016_alter_administrativelevel_unique_together'),
        ('subprojects', '0018_alter_subproject_cantons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='cantons',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='cvds',
        ),
        migrations.AddField(
            model_name='subproject',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='cvd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.cvd'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='link_to_subproject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='subprojects.subproject'),
        ),
    ]
