# Generated by Django 4.1.1 on 2023-06-26 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0019_financier_project_subproject_financier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproject',
            old_name='financier',
            new_name='financiers',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='project',
            new_name='projects',
        ),
    ]
