# Generated by Django 4.1.1 on 2023-03-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0019_remove_subproject_cantons_remove_subproject_cvds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
