# Generated by Django 4.1.1 on 2023-08-01 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0020_rename_financier_subproject_financiers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('wording', models.CharField(max_length=200)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubprojectStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('wording', models.CharField(max_length=200)),
                ('percent', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('begin', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.step')),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.subproject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('wording', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('ranking', models.IntegerField(default=0)),
                ('percent', models.FloatField()),
                ('begin', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('subproject_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subprojects.subprojectstep')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
