# Generated by Django 4.1.1 on 2023-03-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0021_subprojectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subproject',
            old_name='amount_of_care_and_maintenance_fund_raised_and_deposited_in_the_village_account',
            new_name='care_and_maintenance_amount_on_village_account',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='amount_of_the_contract_companies_for_the_supply_of_furniture_and_equipment',
            new_name='contract_companies_amount_for_efme',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='date_signature_contract_companies_supply_of_furniture_and_equipment',
            new_name='date_signature_contract_efme',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='existence_of_a_maintenance_and_upkeep_plan_developed_by_the_Community',
            new_name='existence_of_maintenance_and_upkeep_plan_developed_by_community',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='name_of_the_winning_company_enterprises_of_supply_of_furniture_and_equipment',
            new_name='name_of_company_awarded_efme',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='provisional_acceptance_date_for_furniture_and_equipment_supply_contracts',
            new_name='provisional_acceptance_date_for_efme_contracts',
        ),
        migrations.RenameField(
            model_name='subproject',
            old_name='technical_acceptance_date_for_furniture_and_equipment_supply_contracts',
            new_name='technical_acceptance_date_for_efme_contracts',
        ),
    ]
