# Generated by Django 4.1.1 on 2023-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0022_step_has_levels_alter_level_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='breeders_farmers_group',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='ethnic_minority_group',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='women_s_group',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subproject',
            name='youth_group',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
