# Generated by Django 4.1.1 on 2023-08-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0023_subproject_breeders_farmers_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='joint_project_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
