# Generated by Django 4.1.1 on 2023-08-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0024_subproject_joint_project_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='amount_spent_at_this_step',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount spent at this stage'),
        ),
        migrations.AddField(
            model_name='level',
            name='total_amount_spent',
            field=models.FloatField(blank=True, null=True, verbose_name='Total amount spent'),
        ),
        migrations.AddField(
            model_name='step',
            name='amount_spent_at_this_step',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount spent at this stage'),
        ),
        migrations.AddField(
            model_name='step',
            name='total_amount_spent',
            field=models.FloatField(blank=True, null=True, verbose_name='Total amount spent'),
        ),
        migrations.AddField(
            model_name='subprojectstep',
            name='amount_spent_at_this_step',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount spent at this stage'),
        ),
        migrations.AddField(
            model_name='subprojectstep',
            name='total_amount_spent',
            field=models.FloatField(blank=True, null=True, verbose_name='Total amount spent'),
        ),
    ]
