# Generated by Django 4.1.1 on 2023-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
        ('subprojects', '0027_subproject_subproject_type_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='cvds',
            field=models.ManyToManyField(blank=True, default=[], related_name='cvds_subprojects', to='administrativelevels.cvd', verbose_name='Beneficiary CVD'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='list_of_beneficiary_villages',
            field=models.ManyToManyField(blank=True, default=[], related_name='vilages_subprojects', to='administrativelevels.administrativelevel', verbose_name='Beneficiary villages'),
        ),
    ]
