# Generated by Django 4.1.1 on 2023-08-09 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
        ('subprojects', '0028_subproject_cvds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='cvds',
        ),
        migrations.AlterField(
            model_name='subproject',
            name='list_of_beneficiary_villages',
            field=models.ManyToManyField(blank=True, default=[], related_name='vilages_subprojects', to='administrativelevels.administrativelevel', verbose_name='Beneficiaries villages'),
        ),
    ]
