# Generated by Django 4.1.1 on 2023-08-11 22:16

import cosomis.customers_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
        ('subprojects', '0029_remove_subproject_cvds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='full_title_of_approved_subproject',
            field=models.TextField(max_length=255, verbose_name='Full title of approved sub-project (description)'),
        ),
    ]
