# Generated by Django 4.1.1 on 2023-08-09 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_cvd_name'),
        ('subprojects', '0029_remove_subproject_cvds_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subproject',
            unique_together={('canton', 'full_title_of_approved_subproject'), ('full_title_of_approved_subproject', 'location_subproject_realized', 'subproject_sector', 'type_of_subproject')},
        ),
    ]
