# Generated by Django 4.1.1 on 2023-08-11 23:47

import cosomis.customers_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0030_alter_subproject_full_title_of_approved_subproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='percent',
            field=cosomis.customers_fields.CustomerFloatRangeField(verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='step',
            name='percent',
            field=cosomis.customers_fields.CustomerFloatRangeField(blank=True, null=True, verbose_name='Percent'),
        ),
        migrations.AlterField(
            model_name='subprojectstep',
            name='percent',
            field=cosomis.customers_fields.CustomerFloatRangeField(blank=True, null=True, verbose_name='Percent'),
        ),
    ]
