# Generated by Django 4.1.1 on 2023-10-23 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0032_ministry_subproject_sectoral_ministry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subproject',
            name='sectoral_ministry',
        ),
        migrations.DeleteModel(
            name='Ministry',
        ),
    ]
