# Generated by Django 4.1.1 on 2023-08-11 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subprojects', '0032_alter_level_percent_alter_step_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='full_title_of_approved_subproject',
            field=models.TextField(max_length=255, verbose_name='Full title of approved sub-project (description)'),
        ),
    ]
