# Generated by Django 4.1.1 on 2023-10-24 14:23

from django.db import migrations, models
import django.db.models.deletion


def migrate_investments(apps, schema_editor):
    adm_Investment = apps.get_model("administrativelevels", "Investment")

    inv_Investment = apps.get_model("investments", "Investment")
    inv_Attachment = apps.get_model("investments", "Attachment")

    adm_inv_qs = adm_Investment.objects.all()

    for inv in adm_inv_qs:
        inv_new_obj = inv_Investment.objects.create(
            title=inv.title,
            responsible_structure=inv.responsible_structure,
            administrative_level=inv.administrative_level,
            sector=inv.sector,
            estimated_cost=inv.estimated_cost,
            start_date=inv.start_date,
            duration=inv.duration,
            delays_consumed=inv.delays_consumed,
            physical_execution_rate=inv.physical_execution_rate,
            financial_implementation_rate=inv.financial_implementation_rate,
            investment_status=inv.investment_status,
            project_status=inv.project_status,
            endorsed_by_youth=inv.endorsed_by_youth,
            endorsed_by_women=inv.endorsed_by_women,
            endorsed_by_agriculturist=inv.endorsed_by_agriculturist,
            endorsed_by_pastoralist=inv.endorsed_by_pastoralist,
        )
        att_qs = inv.attachments.all()
        for att_obj in att_qs:
            att_new_obj = inv_Attachment.objects.create(
                adm=att_obj.adm,
                investment=inv_new_obj,
                url=att_obj.url,
                type=att_obj.type,
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrativelevels', '0020_investment_administrative_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('responsible_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_cost', models.PositiveBigIntegerField()),
                ('start_date', models.DateField(null=True)),
                ('duration', models.PositiveIntegerField(help_text='In days')),
                ('delays_consumed', models.PositiveIntegerField(help_text='In days')),
                ('physical_execution_rate', models.PositiveIntegerField(help_text='Percentage')),
                ('financial_implementation_rate', models.PositiveIntegerField(help_text='Percentage')),
                ('investment_status', models.CharField(choices=[('p', 'Priority'), ('s', 'SubProject')], default='p', max_length=30)),
                ('project_status', models.CharField(choices=[('N', 'Not Funded'), ('P', 'In Progress'), ('C', 'Completed')], default='N', max_length=30)),
                ('endorsed_by_youth', models.BooleanField(default=False)),
                ('endorsed_by_women', models.BooleanField(default=False)),
                ('endorsed_by_agriculturist', models.BooleanField(default=False)),
                ('endorsed_by_pastoralist', models.BooleanField(default=False)),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='administrativelevels.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the funding, e.g., a particular organization or grant', max_length=255, null=True)),
                ('draft_status', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution')], default='P', max_length=50)),
                ('funded_investments', models.ManyToManyField(related_name='packages', to='investments.investment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='administrativelevels.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('Photo', 'Photo'), ('Document', 'Document')], default='Document', max_length=10)),
                ('adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrativelevels.administrativelevel')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='investments.investment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(migrate_investments)
    ]
