# Generated by Django 4.1.1 on 2023-11-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending Submission'), ('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution')], default='PS', max_length=50),
        ),
    ]
