# Generated by Django 4.1.1 on 2024-02-15 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_package_status'),
        ('investments', '0002_organization'),
    ]

    operations = [
    ]
