# Generated by Django 4.1.1 on 2023-11-16 08:45

from django.db import migrations, models
import django.db.models.deletion


def init_sector(apps, schema_editor):
    Investment = apps.get_model("investments", "Investment")
    Sector = apps.get_model("administrativelevels", "Sector")
    init_sector_obj = Sector.objects.first()
    if not init_sector_obj:
        Category = apps.get_model("administrativelevels", "Category")
        init_category_obj = Category.objects.first()
        if not init_category_obj:
            init_category_obj = Category.objects.create(
                name='Water'
            )
        init_sector_obj = Sector.objects.create(
            name='Pond',
            description='',
            category=init_category_obj
        )
    investments_qs = Investment.objects.all()
    update_list = list()
    for inv_obj in investments_qs:
        inv_obj.sector = init_sector_obj
        update_list.append(inv_obj)
    Investment.objects.bulk_update(update_list, ['sector'])


def reverse_init_sector(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0025_alter_administrativelevel_type_sector'),
        ('investments', '0002_investment_no_sql_id_investment_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='administrative_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='administrativelevels.administrativelevel'),
        ),
        migrations.RemoveField(
            model_name='investment',
            name='sector'
        ),
        migrations.AddField(
            model_name='investment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='administrativelevels.sector', null=True, blank=True),
        ),
        migrations.RunPython(init_sector, reverse_init_sector),
        migrations.AlterField(
            model_name='investment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='administrativelevels.sector'),
        ),
        migrations.AlterField(
            model_name='package',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='administrativelevels.project'),
        ),
    ]
