# Generated by Django 4.1.1 on 2023-11-16 10:08

from django.conf import settings
from django.db import migrations, models
from investments.models import Package as PackageVariables
import django.db.models.deletion


def init_package_user(apps, schema_editor):
    Package = apps.get_model("investments", "Package")
    User = apps.get_model("auth", "User")
    package_qs = Package.objects.all()
    update_list = list()
    user = User.objects.first()
    if not user:
        user = User.objects.create(
            username='admin',
            email='admin@mail.com'
        )
        user.set_password('open0101')
    for package_obj in package_qs:
        package_obj.user = user
        if package_obj.status == PackageVariables.PENDING_APPROVAL:
            package_obj.status = PackageVariables.REJECTED
        update_list.append(package_obj)
    Package.objects.bulk_update(update_list, ['user', 'status'])


def revert_init_package_user(*args):
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investments', '0003_alter_investment_administrative_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(init_package_user, revert_init_package_user),
        migrations.AlterField(
            model_name='package',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
