# Generated by Django 4.1.1 on 2024-02-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_merge_0002_alter_package_status_0002_organization'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
