# Generated by Django 4.1.1 on 2024-02-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0004_administrativelevel_default_image_and_more'),
        ('investments', '0005_package_no_resubmission_package_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.task'),
        ),
    ]
