# Generated by Django 3.2.21 on 2024-03-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0006_attachment_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='climate_contribution',
            field=models.BooleanField(default=False),
        ),
    ]
