# Generated by Django 4.1.1 on 2024-03-27 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_investment_climate_contribution'),
        ('investments', '0007_remove_package_no_resubmission_alter_package_status'),
    ]

    operations = [
    ]
