# Generated by Django 4.1.1 on 2024-04-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_merge_20240327_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='climate_contribution_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending Submission'), ('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution')], default='PS', max_length=50),
        ),
    ]
