# Generated by Django 4.1.1 on 2024-07-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0014_category_project_end_date_project_start_date_and_more'),
        ('investments', '0009_investment_climate_contribution_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sector',
            name='category',
        ),
        migrations.AlterField(
            model_name='investment',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='administrativelevels.sector'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Sector',
        ),
    ]
