# Generated by Django 4.1.1 on 2024-08-12 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0016_project_owner'),
        ('investments', '0011_investment_latitude_investment_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='funded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrativelevels.project'),
        ),
    ]
