# Generated by Django 4.1.1 on 2024-08-22 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_remove_task_attachments'),
        ('investments', '0013_attachment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrativelevels.task'),
        ),
    ]
