# Generated by Django 4.1.1 on 2024-09-06 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_investment_description_alter_attachment_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='project_status',
            field=models.CharField(choices=[('N', 'Not Funded'), ('F', 'Funded'), ('P', 'In Progress'), ('C', 'Completed'), ('PA', 'Paused')], default='N', max_length=30),
        ),
    ]
