# Generated by Django 4.1.1 on 2024-09-10 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_alter_investment_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
