# Generated by Django 4.1.1 on 2024-10-14 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0019_alter_project_sector'),
        ('investments', '0017_package_review_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='adm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrativelevels.administrativelevel'),
        ),
    ]
