# Generated by Django 4.1.1 on 2025-01-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0022_investment_real_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='acknowledge_by_investor',
            field=models.BooleanField(default=False),
        ),
    ]
