# Generated by Django 4.1.1 on 2025-03-31 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0028_alter_project_end_date_and_more'),
        ('investments', '0023_package_acknowledge_by_investor'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='estimated_cost_by_investor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='funded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='administrativelevels.project'),
        ),
    ]
