# Generated by Django 4.1.1 on 2025-05-06 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0028_alter_project_end_date_and_more'),
        ('investments', '0023_package_acknowledge_by_investor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='funded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='administrativelevels.project'),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending Submission'), ('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution'), ('PA', 'Partially Approved'), ('SG', 'Selected by Government')], default='PS', max_length=50),
        ),
    ]
