# Generated by Django 4.1.1 on 2025-11-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0028_alter_project_end_date_and_more'),
        ('investments', '0024_alter_investment_funded_by_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='came_from',
            field=models.ManyToManyField(blank=True, default=[], related_name='projects_investments', to='administrativelevels.project'),
        ),
    ]
