# Generated by Django 4.1.1 on 2026-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0025_investment_came_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='process_moment',
            field=models.CharField(choices=[('Community Process', 'Community Process'), ('Infrastructure in Progress', 'Infrastructure in Progress'), ('Completed Infrastructure', 'Completed Infrastructure')], default='Community Process', max_length=50),
        ),
        migrations.AddField(
            model_name='attachment',
            name='source',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
