# Generated by Django 4.1.1 on 2026-03-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0026_attachment_description_attachment_process_moment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='abandoned_in_the_meantime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='abandonment_history',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
