# Generated by Django 4.1.1 on 2026-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0027_investment_abandoned_in_the_meantime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending Submission'), ('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution'), ('PA', 'Partially Approved'), ('SG', 'Selected by Government'), ('C', 'Closed')], default='PS', max_length=50),
        ),
    ]
