# Generated by Django 4.1.1 on 2026-05-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0027_investment_abandoned_in_the_meantime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
