# Generated by Django 4.1.1 on 2026-08-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0033_groupesocioeconomique_component'),
        ('investments', '0028_alter_package_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='administrative_levels',
            field=models.ManyToManyField(blank=True, related_name='co_investments', to='administrativelevels.administrativelevel'),
        ),
        migrations.AddField(
            model_name='investment',
            name='beneficiaries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investment',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='administrativelevels.component'),
        ),
        migrations.AddField(
            model_name='investment',
            name='endorsed_by_displaced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='investment',
            name='groupes_socioeconomiques',
            field=models.ManyToManyField(blank=True, related_name='investments', to='administrativelevels.groupesocioeconomique'),
        ),
        migrations.AddField(
            model_name='investment',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='estimated_cost',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('PS', 'Pending Submission'), ('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution'), ('PA', 'Partially Processed'), ('SG', 'Selected by Government'), ('C', 'Closed')], default='PS', max_length=50),
        ),
        migrations.CreateModel(
            name='GroupInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('administrative_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_investments', to='administrativelevels.administrativelevel')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_investments', to='administrativelevels.component')),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_investments_as_lieu', to='administrativelevels.administrativelevel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='investment',
            name='group_investment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='investments.groupinvestment'),
        ),
    ]
