# Generated by Django 4.1.1 on 2026-06-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0028_alter_investment_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='sub_component',
            field=models.CharField(blank=True, choices=[('1.1', '1.1'), ('1.2a', '1.2a'), ('1.2b', '1.2b'), ('1.3', '1.3')], max_length=10, null=True, verbose_name='Sub Component'),
        ),
    ]
