# Generated by Django 4.1.1 on 2026-06-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0029_investment_sub_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='endorsed_by_chiefs',
            field=models.BooleanField(default=False),
        ),
    ]
