# Generated by Django 4.1.1 on 2026-07-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0030_investment_endorsed_by_chiefs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='project_status',
            field=models.CharField(choices=[('N', 'Not Funded'), ('F', 'Funded'), ('P', 'In Progress'), ('C', 'Completed'), ('PA', 'Paused'), ('FNS', 'Funded — not started')], default='N', max_length=30),
        ),
    ]
