# Generated by Django 4.1.1 on 2024-01-18 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0002_phase_activity_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='administrativelevels.phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='administrativelevels.administrativelevel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='administrativelevels.activity'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('in progress', 'in progress'), ('completed', 'completed'), ('error', 'error')], default='not started', max_length=127),
        ),
    ]
