# Generated by Django 4.1.1 on 2024-02-20 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_package_no_resubmission_package_rejection_reason'),
        ('administrativelevels', '0003_alter_activity_phase_alter_phase_village_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='default_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investments.attachment'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='identified_priority',
            field=models.DateField(blank=True, null=True),
        ),
    ]
