# Generated by Django 4.1.1 on 2022-10-05 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0004_village'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='village',
            name='administrative_level',
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.village'),
        ),
    ]
