# Generated by Django 4.1.1 on 2024-02-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0005_task_form_responses"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="no_sql_db_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="phase",
            name="no_sql_db_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="no_sql_db_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
