# Generated by Django 4.1.1 on 2024-02-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0007_alter_activity_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="phase",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together=set(),
        ),
    ]
