# Generated by Django 4.1.1 on 2024-02-25 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0008_alter_activity_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("phase", "order", "no_sql_db_id")},
        ),
        migrations.AlterUniqueTogether(
            name="phase",
            unique_together={("village", "order", "no_sql_db_id")},
        ),
        migrations.AlterUniqueTogether(
            name="task",
            unique_together={("activity", "order", "no_sql_db_id")},
        ),
    ]
