# Generated by Django 4.1.1 on 2023-02-24 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0009_unitgeographic_cvd_administrativelevel_cvd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnitGeographic',
            new_name='GeographicalUnit',
        ),
    ]
