# Generated by Django 4.1.1 on 2024-02-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administrativelevels", "0010_alter_activity_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="form",
            field=models.TextField(
                blank=True,
                help_text="This is a json field that needs to be parsed.",
                null=True,
            ),
        ),
    ]
