# Generated by Django 4.1.1 on 2024-03-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0012_task_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='form',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='form_responses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
