# Generated by Django 4.1.1 on 2024-07-21 15:39

from django.db import migrations, models
import django.db.models.deletion


def migrate_sectors_and_categories(apps, schema_editor):
    OldCategory = apps.get_model('investments', 'Category')
    NewCategory = apps.get_model('administrativelevels', 'Category')
    OldSector = apps.get_model('investments', 'Sector')
    NewSector = apps.get_model('administrativelevels', 'Sector')

    new_categories = list()
    for category in OldCategory.objects.all():
        new_categories.append(NewCategory(
            name=category.name,
            description=category.description,
        ))
    NewCategory.objects.bulk_create(new_categories)

    new_sectors = list()
    for sector in OldSector.objects.all():
        cat = NewCategory.objects.get(name=sector.category.name)
        new_sectors.append(NewSector(
            name=sector.name,
            description=sector.description,
            category=cat
        ))
    NewSector.objects.bulk_create(new_sectors)


def rev_migrate_sectors_and_categories(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0013_alter_task_attachments_alter_task_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='administrativelevels.administrativelevel', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='type',
            field=models.CharField(choices=[('Village', 'Village'), ('Canton', 'Canton'), ('Commune', 'Commune'), ('Prefecture', 'Prefecture'), ('Region', 'Region')], default='Village', max_length=255, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.sector'),
        ),
        migrations.RunPython(migrate_sectors_and_categories, rev_migrate_sectors_and_categories)
    ]
