# Generated by Django 4.1.1 on 2024-07-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0014_category_project_end_date_project_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_agency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Implementation agency'),
        ),
    ]
