# Generated by Django 4.1.1 on 2024-08-20 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0016_project_owner'),
        ('investments', '0013_attachment_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='attachments',
        ),
    ]
