# Generated by Django 5.1.1 on 2024-09-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_remove_task_attachments'),
        ('usermanager', '0002_user_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='implementation_agency',
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='usermanager.organization', verbose_name='Implementation agency'),
        ),
    ]
