# Generated by Django 4.1.1 on 2024-08-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0017_remove_task_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
