# Generated by Django 4.1.1 on 2023-09-01 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_bank_alter_administrativelevelallocation_table'),
        ('administrativelevels', '0017_cvd_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvd',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account number'),
        ),
        migrations.AddField(
            model_name='cvd',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financial.bank', verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='cvd',
            name='bank_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Bank code'),
        ),
        migrations.AddField(
            model_name='cvd',
            name='guichet_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Guichet code'),
        ),
        migrations.AddField(
            model_name='cvd',
            name='rib',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='RIB'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='cvd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.cvd', verbose_name='CVD'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='frontalier',
            field=models.BooleanField(default=True, verbose_name='Frontalier'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='geographical_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.geographicalunit', verbose_name='Geographical unit'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='rural',
            field=models.BooleanField(default=True, verbose_name='Rural'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='attributed_number_in_canton',
            field=models.IntegerField(blank=True, null=True, verbose_name='Attributed number in canton'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='geographical_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.geographicalunit', verbose_name='Geographical unit'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='headquarters_village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headquarters_village_of_the_cvd', to='administrativelevels.administrativelevel', verbose_name='Headquarters village'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='president_name_of_the_cvd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='President name of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='president_phone_of_the_cvd',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='President phone of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='secretary_name_of_the_cvd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Secretary name of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='secretary_phone_of_the_cvd',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Secretary phone of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='treasurer_name_of_the_cvd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Treasurer name of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='treasurer_phone_of_the_cvd',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Treasurer phone of the CVD'),
        ),
        migrations.AlterField(
            model_name='cvd',
            name='unique_code',
            field=models.CharField(max_length=100, verbose_name='Unique code'),
        ),
        migrations.AlterField(
            model_name='geographicalunit',
            name='attributed_number_in_canton',
            field=models.IntegerField(verbose_name='Attributed number in canton'),
        ),
        migrations.AlterField(
            model_name='geographicalunit',
            name='canton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel', verbose_name='Administrative level'),
        ),
        migrations.AlterField(
            model_name='geographicalunit',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='geographicalunit',
            name='unique_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Unique code'),
        ),
    ]
