# Generated by Django 4.1.1 on 2023-10-20 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0018_cvd_account_number_cvd_bank_cvd_bank_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('responsible_structure', models.CharField(blank=True, max_length=255, null=True)),
                ('estimated_cost', models.PositiveBigIntegerField()),
                ('start_date', models.DateField(null=True)),
                ('duration', models.PositiveIntegerField(help_text='In days')),
                ('delays_consumed', models.PositiveIntegerField(help_text='In days')),
                ('physical_execution_rate', models.PositiveIntegerField(help_text='Percentage')),
                ('financial_implementation_rate', models.PositiveIntegerField(help_text='Percentage')),
                ('investment_status', models.CharField(choices=[('p', 'Priority'), ('s', 'SubProject')], default='p', max_length=30)),
                ('project_status', models.CharField(choices=[('N', 'Not Funded'), ('P', 'In Progress'), ('C', 'Completed')], default='N', max_length=30)),
                ('endorsed_by_youth', models.BooleanField(default=False)),
                ('endorsed_by_women', models.BooleanField(default=False)),
                ('endorsed_by_agriculturist', models.BooleanField(default=False)),
                ('endorsed_by_pastoralist', models.BooleanField(default=False)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='administrativelevels.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('implementation_agency', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='main_languages',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_agriculturist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_elder',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_handicap',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_men',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_minorities',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_pastoralist',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_women',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='population_young',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='status_color',
            field=models.CharField(choices=[('lime_green', 'Lime Green'), ('dark_green', 'Dark Green'), ('orange', 'Orange'), ('red', 'Red')], default='lime_green', max_length=20),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='status_description',
            field=models.CharField(choices=[('early', 'Early'), ('normal', 'Normal'), ('late', 'Late'), ('blocked', 'Blocked')], default='normal', max_length=15),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='total_population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='administrativelevel',
            name='type',
            field=models.CharField(choices=[('village', 'Village'), ('canton', 'Canton'), ('commune', 'Commune'), ('region', 'Region')], default='village', max_length=255, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the funding, e.g., a particular organization or grant', max_length=255, null=True)),
                ('draft_status', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('P', 'Pending Approval'), ('A', 'Approved'), ('R', 'Rejected'), ('E', 'Under Execution')], default='P', max_length=50)),
                ('funded_investments', models.ManyToManyField(related_name='packages', to='administrativelevels.investment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='administrativelevels.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('Photo', 'Photo'), ('Document', 'Document')], default='Document', max_length=10)),
                ('adm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='administrativelevels.administrativelevel')),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to='administrativelevels.investment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
