# Generated by Django 3.2.21 on 2023-10-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0019_category_investment_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='activity',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='attachment',
            name='phase',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='attachment',
            name='task',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
