# Generated by Django 4.1.1 on 2024-10-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0019_alter_project_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='code_loc',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Code location'),
        ),
    ]
