# Generated by Django 3.2.21 on 2023-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0020_auto_20231022_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='activity',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='phase',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='task',
            field=models.CharField(max_length=10),
        ),
    ]
