# Generated by Django 4.1.1 on 2023-10-24 13:53

from django.db import migrations, models
import django.db.models.deletion


def init_administrative_level(apps, schema_editor):
    Investment = apps.get_model("administrativelevels", "Investment")
    AdministrativeLevel = apps.get_model("administrativelevels", "AdministrativeLevel")
    adm_lvl = AdministrativeLevel.objects.first()
    if adm_lvl is not None:
        qs = Investment.objects.all()
        for obj in qs:
            obj.administrative_level = adm_lvl
            obj.save()


def reverse_init_administrative_level(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0021_auto_20231022_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='administrative_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(init_administrative_level, reverse_init_administrative_level),
        migrations.AlterField(
            model_name='investment',
            name='administrative_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.administrativelevel'),
        )
    ]
