# Generated by Django 3.2.25 on 2024-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0021_geosegment'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
