# Generated by Django 4.1.1 on 2023-10-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0022_investment_administrative_level'),
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='administrative_level',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='sector',
        ),
        migrations.RemoveField(
            model_name='package',
            name='funded_investments',
        ),
        migrations.RemoveField(
            model_name='package',
            name='project',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
        migrations.DeleteModel(
            name='Investment',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
    ]
