# Generated by Django 3.2.25 on 2024-11-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0022_auto_20241116_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='facilitator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
