# Generated by Django 4.1.1 on 2024-11-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0023_auto_20241117_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_of_financing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
