# Generated by Django 4.1.1 on 2023-11-16 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0024_administrativelevel_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrativelevel',
            name='type',
            field=models.CharField(choices=[('Village', 'Village'), ('Canton', 'Canton'), ('Commune', 'Commune'), ('Region', 'Region'), ('Prefecture', 'Prefecture')], default='Village', max_length=255, verbose_name='Type'),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrativelevels.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
