# Generated by Django 4.1.1 on 2024-12-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0025_administrativelevel_geo_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='infrastructure',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
