# Generated by Django 4.1.1 on 2025-02-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0026_administrativelevel_infrastructure'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='collaborators',
            new_name='implementation_partner',
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_partner',
            field=models.TextField(blank=True, help_text='e.g., WORLD BANK,UNFPA,WFP', null=True)
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='project',
            name='sector',
        ),
        migrations.AlterField(
            model_name='project',
            name='source_of_financing',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Source of financing'),
        ),
        migrations.AddField(
            model_name='project',
            name='sectors',
            field=models.ManyToManyField(to='administrativelevels.category'),
        ),
    ]
