# Generated by Django 4.1.1 on 2025-03-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0027_remove_project_collaborators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='implementation_partner',
            field=models.TextField(blank=True, help_text='e.g., WORLD BANK,UNFPA,WFP', null=True, verbose_name='Implementation partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='sectors',
            field=models.ManyToManyField(to='administrativelevels.category', verbose_name='Sectors'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start date'),
        ),
    ]
