# Generated by Django 4.1.1 on 2026-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0028_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='is_headquarters',
            field=models.BooleanField(default=False),
        ),
    ]
