# Generated by Django 4.1.1 on 2026-06-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0028_alter_project_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('administrative_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='administrativelevels.administrativelevel')),
            ],
            options={
                'unique_together': {('name', 'administrative_level')},
            },
        ),
    ]
