# Generated by Django 4.1.1 on 2026-08-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0029_administrativelevel_is_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='total_house_holds',
            field=models.IntegerField(default=0),
        ),
    ]
