# Generated by Django 4.1.1 on 2026-08-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0030_administrativelevel_total_house_holds'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='minorities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
