# Generated by Django 4.1.1 on 2026-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0031_administrativelevel_minorities'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='ethnic_groups',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
