# Generated by Django 4.1.1 on 2026-08-13 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0033_groupesocioeconomique_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phases', to='administrativelevels.project'),
        ),
    ]
