# Generated by Django 4.1.1 on 2026-08-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0034_phase_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not started', 'not started'), ('in progress', 'in progress'), ('completed', 'completed'), ('error', 'error'), ('validated', 'validated'), ('invalidated', 'invalidated')], default='not started', max_length=127),
        ),
    ]
