# Generated by Django 4.1.1 on 2026-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0035_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
