# Generated by Django 4.1.1 on 2026-10-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativelevels', '0036_component_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_validated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='validated',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
